apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-gateway
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy-gateway

  source:
    repoURL: https://haproxytech.github.io/helm-charts
    chart: kubernetes-ingress
    targetRevision: "1.47.4"
    helm:
      releaseName: haproxy-ingress
      skipCrds: true
      values: |
        gatewayAPI:
          enabled: true
        controller:
          kubernetesGateway:
            enabled: true
            gatewayControllerName: haproxy.org/gateway-controller
          replicaCount: 1
          service:
            type: NodePort

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
