apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: backend
spec:
  parentRefs:
    - name: prod-gateway
      namespace: envoy-gateway
      sectionName: http
