apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  namespace: elastic-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      containers:
      - name: exporter
        image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.7.0
        env:
        - name: ES_USERNAME
          valueFrom:
            secretKeyRef:
              name: es-exporter-credentials
              key: ES_USERNAME
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: es-exporter-credentials
              key: ES_PASSWORD
        args:
          - '--es.uri=https://$(ES_USERNAME):$(ES_PASSWORD)@elastic-prod-es-http.elastic-prod.svc:9200'
          - '--es.ssl-skip-verify'
        ports:
        - name: metrics
          containerPort: 9114
