apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  namespace: elastic-prod
  labels:
    app: elasticsearch-exporter
spec:
  selector:
    app: elasticsearch-exporter
  ports:
  - name: metrics
    port: 9114
    targetPort: 9114
