apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elasticsearch
  namespace: elastic-prod
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: elasticsearch-exporter
  namespaceSelector:
    matchNames:
      - elastic-prod
  endpoints:
  - port: metrics
    interval: 30s
