apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
---
# Instead of manually adding CRDs, reference Elastic's all-in-one manifest
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://download.elastic.co/downloads/eck/2.12.0
    targetRevision: HEAD
    path: all-in-one.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
